export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const SHOW_DELETE_MESSAGE = "SHOW_DELETE_MESSAGE";
export const HIDE_DELETE_MESSAGE = "HIDE_DELETE_MESSAGE";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const EMPTY_BASKET = "EMPTY_BASKET";
